fdbc: action_lib.c File Reference
action_lib.c File Reference
#include "action_lib.h"
#include "log_lib.h"
#include "conf_lib.h"
Functions
void on_accept (int fd, short ev, void *arg)
void conn_new (int sfd, struct event_base *base)
void procThread ()
void * fproc (void *arg)
Function Documentation
void conn_new (int sfd, struct event_base * base)
Definition at line 63 of file action_lib.c.
References conns, conn::event, on_accept(), and conn::sfd.
Referenced by main().
{
        conns = (conn *)calloc(1, sizeof(conn));
        conns->sfd = sfd;
        event_set(&conns->event, sfd, EV_READ|EV_PERSIST, on_accept, (void *)conns);
        event_base_set(base, &conns->event);
        event_add(&conns->event, 0);
}
void* fproc (void * arg)
Definition at line 102 of file action_lib.c.
References hproc(), NT_FREE, NT_WORKING, and proc_status.
Referenced by procThread().
{
    proc_status = NT_WORKING;
    hproc();
    proc_status = NT_FREE;
}               /* -----  end of function fproc  ----- */
void on_accept (int fd, short ev, void * arg)
Definition at line 14 of file action_lib.c.
References d_log(), notify_token_thread, NT_FREE, proc_status, procThread(), rq_push(), and token_efd.
Referenced by conn_new().
{
        int client_fd, err_len;
    char *err, *err_log;
        struct sockaddr_in client_addr;
        socklen_t client_len;
    LIBEVENT_WORK_THREAD *thread;
    client_len = sizeof(client_addr);
    uint64_t u;
    ssize_t s;
    extern NOTIFY_TOKEN_STATE notify_token_thread;
    extern int token_efd;
        /* Accept the new connection. */
        client_fd = accept(fd, (struct sockaddr *)&client_addr, &client_len);
        if (client_fd == -1) {
        err = strerror(errno);
        err_len = strlen(err);
        err_log = calloc(1, err_len+10);
        sprintf(err_log, "accept-- %s", err);
                d_log(err_log);
        free(err_log);
                return;
        }
    if(rq_push(client_fd) == 0){
        if(notify_token_thread == NT_FREE){
            /*  thread = work_threads+1;
              write(thread->notify_write_fd, "", 1);
                 token_sem_post();*/
             u = 1;
             s = write(token_efd, &u , sizeof(uint64_t));
             if(s != sizeof(uint64_t))printf("error---\n");
        }else{
            printf("accept error\n");
        }
    }else{
        close(client_fd);
        d_log("RQ is full");
    }
    if(proc_status == NT_FREE){
        procThread();
    }
}
void procThread (void)
Definition at line 80 of file action_lib.c.
References d_log(), fproc(), NT_HAS, and proc_status.
Referenced by on_accept().
                    {
    pthread_t       thread;
    pthread_attr_t  attr;
    int ret;
    pthread_attr_init(&attr);
    proc_status = NT_HAS;
    if ((ret = pthread_create(&thread, &attr, fproc, NULL)) != 0) {
        d_log("Can't create thread");
        printf("here---\n");
        exit(1);
    }
}               /* -----  end of function procThread  ----- */