fdbc: action_lib.h File Reference
action_lib.h File Reference
#include "thread_lib.h"
#include "./hashtable/pool_proc.h"
Functions
void do_dispatch (int fd, short ev, void *arg)
void conn_new (int sfd, struct event_base *base)
void procThread (void)
void * fproc (void *arg)
Variables
NOTIFY_TOKEN_STATE proc_status
Function Documentation
void conn_new (int sfd, struct event_base * base)
Definition at line 63 of file action_lib.c.
References conns, conn::event, on_accept(), and conn::sfd.
Referenced by main().
{
        conns = (conn *)calloc(1, sizeof(conn));
        conns->sfd = sfd;
        event_set(&conns->event, sfd, EV_READ|EV_PERSIST, on_accept, (void *)conns);
        event_base_set(base, &conns->event);
        event_add(&conns->event, 0);
}
void do_dispatch (int fd, short ev, void * arg)
void* fproc (void * arg)
Definition at line 102 of file action_lib.c.
References hproc(), NT_FREE, NT_WORKING, and proc_status.
Referenced by procThread().
{
    proc_status = NT_WORKING;
    hproc();
    proc_status = NT_FREE;
}               /* -----  end of function fproc  ----- */
void procThread (void)
Definition at line 80 of file action_lib.c.
References d_log(), fproc(), NT_HAS, and proc_status.
Referenced by on_accept().
                    {
    pthread_t       thread;
    pthread_attr_t  attr;
    int ret;
    pthread_attr_init(&attr);
    proc_status = NT_HAS;
    if ((ret = pthread_create(&thread, &attr, fproc, NULL)) != 0) {
        d_log("Can't create thread");
        printf("here---\n");
        exit(1);
    }
}               /* -----  end of function procThread  ----- */
Variable Documentation
NOTIFY_TOKEN_STATE proc_status
Definition at line 15 of file action_lib.h.
Referenced by fproc(), on_accept(), and procThread().