fdbc: conf_lib.c File Reference
conf_lib.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "conf_lib.h"
Functions
char * Trims (char *srcVal)
void conf_init (char *path)
char * conf_get (char *val)
Function Documentation
char* conf_get (char * val)
Definition at line 70 of file conf_lib.c.
Referenced by conn_get_global(), libevent_work_thread(), server_socket_unix(), and Socket_Init().
{
        char *p;
        if((p = getenv(val)) == NULL){
                printf("can't get val conf: %s\n", val);
        }
        return p;
}
void conf_init (char * path)
Definition at line 35 of file conf_lib.c.
References Trims().
Referenced by main().
{
        FILE *fp;
    char *p, *right_val, *left_val;
        char buf[100], bufs[100];
        fp = fopen(path, "r");
        assert((fp!=NULL));
        while(!feof(fp)){
                fgets(buf,2, fp);
                if(!strcmp(buf, "#")){
                        fgets(buf, 100, fp);
                }else if(!strcmp(buf, "[")){
                        fgets(buf, 100, fp);
                }else{
                        fgets(bufs, 100, fp);
                        if(bufs[strlen(bufs)-1] == '\n')
                                bufs[strlen(bufs)-1] = ' ';
                        p = strcat(buf, bufs);
                        left_val = strtok(p, "=");
                        right_val = strtok(NULL, "=");
                        left_val = Trims(left_val);
                        right_val = Trims(right_val);
                        if(left_val == NULL)continue;
                        if(right_val == NULL) setenv(left_val,"",1);
                        else setenv(left_val, right_val, 1);
                }
        }
        fclose(fp);
}
char* Trims (char * srcVal)
Definition at line 16 of file conf_lib.c.
Referenced by conf_init().
{
        char *cp1 = srcVal, *cp2 = srcVal;
        if(srcVal){
                while(*cp1 == ' ')
                        cp1++;
                while(*cp1)
                        *cp2++ = *cp1++;
                if(cp2 != srcVal){
                        while(*--cp2 == ' ');
                        *(cp2+1) = 0;
                }else
                   *srcVal = 0;
        }
        return srcVal;
}