fdbc: config_global.c File Reference
config_global.c File Reference
#include "config_global.h"
Functions
void conn_init_global (void)
void conn_get_global ()
Function Documentation
void conn_get_global ()
Definition at line 53 of file config_global.c.
References conf_get(), and conn_global.
Referenced by main().
{
    conn_global->server_ip = conf_get("server_ip");
    conn_global->server_port = atoi(conf_get("server_port"));
    conn_global->unix_sock = atoi(conf_get("unix_sock"));
    conn_global->path = conf_get("path");
    conn_global->pg_host = conf_get("pg_host");
    conn_global->pg_port = atoi(conf_get("pg_port"));
    conn_global->do_daemonize = atoi(conf_get("do_daemonize"));
    conn_global->pid_file = conf_get("pid_file");
    conn_global->process_num = atoi(conf_get("process_num"));
    conn_global->factor = 1.25;
    conn_global->maxbytes = 64 * 1024 * 1024;
    return ;
}               /* -----  end of function conn_get_global  ----- */
void conn_init_global (void)
Definition at line 26 of file config_global.c.
References conn_global.
Referenced by main().
{
    conn_global = (_conn *)calloc(1, sizeof(_conn));
    conn_global->server_ip = "localhost";
    conn_global->server_port = 8008;
    conn_global->unix_sock = 0;
    conn_global->path = "/tmp/sqlproxy.sock";
    conn_global->pg_host = "localhost";
    conn_global->pg_port = 5432;
    conn_global->do_daemonize = 0;
    conn_global->pid_file = "/var/run/server.pid";
    conn_global->process_num = 2;
    conn_global->factor = 1.25;
    conn_global->maxbytes = 64 * 1024 * 1024 ;
}               /* -----  end of function conn_init_global  ----- */