fdbc: daemon_lib.h File Reference
daemon_lib.h File Reference
#include <sys/types.h>
#include <unistd.h>
#include <signal.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <error.h>
#include "log_lib.h"
Functions
int daemon_init (const char *pname, int facility)
void save_pid (const pid_t pid, const char *pid_file)
void remove_pidfile (const char *pid_file)
Function Documentation
int daemon_init (const char * pname, int facility)
Definition at line 15 of file daemon_lib.c.
References MAXFD.
Referenced by main().
{
        int i;
        pid_t pid;
        char id[10];
        if((pid = fork()) < 0)
                return (-1);
        else if(pid)
                _exit(0);
        if(setsid() < 0)
                return(-1);
        signal(SIGHUP, SIG_IGN);
        if((pid = fork()) < 0)
                return (-1);
        else if(pid)
                _exit(0);
        chdir("/");
        for(i=0; i<MAXFD; i++)
                close(i);
        sprintf(id, "%d\n", getpid());
        open("/dev/null", O_RDONLY);
        open("/dev/null", O_RDWR);
        open("/dev/null", O_RDWR);
        return(0);
}
void remove_pidfile (const char * pid_file)
Definition at line 65 of file daemon_lib.c.
References d_log().
{
  if (pid_file == NULL)
      return;
  if (unlink(pid_file) != 0) {
      d_log("Could not remove the pid file ");
  }
}
void save_pid (const pid_t pid, const char * pid_file)
Definition at line 48 of file daemon_lib.c.
References d_log().
Referenced by main().
{
    FILE *fp;
    if (pid_file == NULL)
        return;
    if ((fp = fopen(pid_file, "w")) == NULL) {
        d_log("Could not open the pid file  for writing");
        return;
    }
    fprintf(fp,"%ld\n", (long)pid);
    if (fclose(fp) == -1) {
        d_log("Could not close the pid file ");
        return;
    }
}