fdbc: dict_lib.h File Reference
dict_lib.h File Reference
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <stdio.h>
Data Structures
struct FieldName
struct DICT_ARRAY
struct DICT_LINK
Functions
DICT_LINK * dict_init (void)
DICT_ARRAY * dict_add (FieldName const *fields, char **value, unsigned int num_field)
int dict_length (DICT_LINK *head)
DICT_LINK * dict_find_link (DICT_LINK *head, DICT_ARRAY *da_head)
DICT_ARRAY * dict_find_array (DICT_ARRAY *head, char *find_field)
FieldName * field_init (void)
void field_add (FieldName **head, char *fn, int type)
void dict_free (DICT_LINK *head)
void field_free (FieldName *head)
Function Documentation
DICT_ARRAY* dict_add (FieldName const * fields, char ** value, unsigned int num_field)
Definition at line 19 of file dict_lib.c.
References DICT_ARRAY::field, FieldName::fn, FieldName::next, DICT_ARRAY::next, and DICT_ARRAY::value.
{
        DICT_ARRAY *array_run, *array_head;
        FieldName const *fn_run;
        int m = num_field-1;
        fn_run = fields;
        array_head = NULL;
        while(fn_run != NULL && fn_run->fn != NULL){
                array_run = (DICT_ARRAY *)calloc(1, sizeof(DICT_ARRAY));
                array_run->value = value[m]!=NULL ? strdup(value[m]) : value[m];
                array_run->field = fn_run->fn ? strdup(fn_run->fn) : fn_run->fn;
        array_run->next = array_head;
                array_head = array_run;
                fn_run = fn_run->next;
                m--;
        }
        return array_head;
}
DICT_ARRAY* dict_find_array (DICT_ARRAY * head, char * find_field)
Definition at line 70 of file dict_lib.c.
References DICT_ARRAY::field, and DICT_ARRAY::next.
{
    DICT_ARRAY *d;
    d = head;
    for(;d;d=d->next){
        if(strcmp(d->field, find_field) == 0)return d;
    }
    return d;
}
DICT_LINK* dict_find_link (DICT_LINK * head, DICT_ARRAY * da_head)
Definition at line 86 of file dict_lib.c.
References dict_find_link_base().
{
    return dict_find_link_base(head, da_head, 0);
}
void dict_free (DICT_LINK * head)
Definition at line 112 of file dict_lib.c.
References DICT_LINK::da, DICT_ARRAY::field, DICT_ARRAY::next, DICT_LINK::next, and DICT_ARRAY::value.
Referenced by mod_class().
{
        DICT_LINK *link_del, *link_run;
        DICT_ARRAY *array_del, *array_run;
        link_run = head;
        while(link_run != NULL){
                link_del = link_run;
                array_run = link_del->da;
                link_run = link_run->next;
                while(array_run != NULL){
                        array_del = array_run;
                        array_run = array_run->next;
                        free(array_del->field);
                        free(array_del->value);
                        free(array_del);
                }
                free(link_del);
        }
}
DICT_LINK* dict_init (void)
Definition at line 12 of file dict_lib.c.
References DICT_LINK::da.
{
        DICT_LINK *dl;
        dl = (DICT_LINK *)calloc(1, sizeof(DICT_LINK));
        dl->da = NULL;
        return dl;
}
int dict_length (DICT_LINK * head)
Definition at line 40 of file dict_lib.c.
References DICT_LINK::next.
{
    DICT_LINK *l;
    int i=0;
    l = head;
    for(;l;l=l->next)i++;
    return i;
}
void field_add (FieldName ** head, char * fn, int type)
Definition at line 98 of file dict_lib.c.
References field_init(), FieldName::fn, and FieldName::next.
{
        FieldName *nfn;
        nfn = field_init();
        if(fn != NULL){
                if(type == 0)
                        nfn->fn = strdup(fn);
                else
                        nfn->fn = strdup("_0");
        }
        nfn->next = *head;
        *head = nfn;
}
void field_free (FieldName * head)
Definition at line 133 of file dict_lib.c.
References FieldName::fn, and FieldName::next.
{
        FieldName *fn_del, *fn_run;
        fn_run = head;
        while(fn_run != NULL){
                fn_del = fn_run;
                fn_run = fn_run->next;
                free(fn_del->fn);
                free(fn_del);
        }
}
FieldName* field_init (void)
Definition at line 91 of file dict_lib.c.
References FieldName::fn.
Referenced by field_add().
{
        FieldName *fn_head;
        fn_head = (FieldName *)calloc(1, sizeof(FieldName));
        fn_head->fn = NULL;
        return fn_head;
}