fdbc: error_lib.h File Reference
error_lib.h File Reference
#include <pthread.h>
#include <malloc.h>
Data Structures
struct ERROR_LIST
Defines
#define ERROR_QUERY 1
#define ERROR_SQL 2
Functions
void error_init (int error_num)
void error_add (pid_t pid)
ERROR_LIST * error_find (void)
void error_store (int eid)
int error_get (void)
Variables
ERROR_LIST * err_list
ERROR_LIST * user_errls
Define Documentation
#define ERROR_QUERY 1
Definition at line 15 of file error_lib.h.
#define ERROR_SQL 2
Definition at line 16 of file error_lib.h.
Function Documentation
void error_add (pid_t pid)
Definition at line 27 of file error_lib.c.
References user_errls.
{
        user_errls->pid = pid;
        user_errls = user_errls->next;
}
ERROR_LIST* error_find (void)
Definition at line 35 of file error_lib.c.
References err_list.
Referenced by error_get(), and error_store().
{
        ERROR_LIST *fel;
        pid_t pid;
        pid = pthread_self();
        fel = err_list;
        for(;fel && fel->pid != pid; fel=fel->next);
        return fel;
}
int error_get (void)
Definition at line 59 of file error_lib.c.
References error_find().
                   {
        ERROR_LIST *gel;
    int el;
        gel = error_find();
    el = gel->reflag;
    gel->reflag = 0;
        return el;
}
void error_init (int error_num)
Definition at line 12 of file error_lib.c.
References err_list, and user_errls.
{
        int i;
        ERROR_LIST *el;
        err_list = NULL;
        for(i=0; i<error_num; i++){
                el = (ERROR_LIST *)calloc(1, sizeof(ERROR_LIST));
                el->next = err_list;
                err_list = el;
        }
        user_errls = err_list;
}
void error_store (int eid)
Definition at line 48 of file error_lib.c.
References error_find().
{
        ERROR_LIST *sel;
        sel = error_find();
    if(NULL != sel){
        sel->reflag = eid;
    }
}
Variable Documentation
ERROR_LIST* err_list
Definition at line 26 of file error_lib.h.
Referenced by error_find(), and error_init().
ERROR_LIST* user_errls
Definition at line 27 of file error_lib.h.
Referenced by error_add(), and error_init().