fdbc: hashtable/lookupa.h File Reference
hashtable/lookupa.h File Reference
#include "pool_struct.h"
Defines
#define CHECKSTATE 8
#define hashsize(n) ((ub4)1<<(n))
#define hashmask(n) (hashsize(n)-1)
Functions
ub4 lookup ()
void checksum ()
ub4 jenkins_one_at_a_time_hash (ub1 *key, size_t len)
Define Documentation
#define CHECKSTATE 8
Definition at line 17 of file lookupa.h.
#define hashmask (n) (hashsize(n)-1)
Definition at line 19 of file lookupa.h.
#define hashsize (n) ((ub4)1<<(n))
Definition at line 18 of file lookupa.h.
Function Documentation
void checksum ()
ub4 jenkins_one_at_a_time_hash (ub1 * key, size_t len)
Definition at line 240 of file lookupa.c.
Referenced by fetchdti(), haddHitem(), and hfind().
{
    ub4 hash, i;
    for(hash = i = 0; i < len; ++i)
    {
        hash += key[i];
        hash += (hash << 10);
        hash ^= (hash >> 6);
    }
    hash += (hash << 3);
    hash ^= (hash >> 11);
    hash += (hash << 15);
    return hash;
}
ub4 lookup ()