fdbc: hashtable/pool_worker.c File Reference
hashtable/pool_worker.c File Reference
#include "pool_worker.h"
Functions
void hkey (char *key, ub4 keyl, SLABPACK *dest)
HITEM * hfind (char *key, ub4 keyl)
void getslab (HITEM *hitem, SLABPACK *dest)
int addHdr (HDR *myhdr, int m)
int addUlist (ULIST *mlist, int m)
void freeHdr (HDR *fhdr)
void freeUList (ULIST *flist)
Function Documentation
int addHdr (HDR * myhdr, int m)
Definition at line 134 of file pool_worker.c.
References freeHdr(), H_FALSE, LIMIT_SLAB_BYTE, and pools_hdr.
Referenced by main().
{
    HDR *_hdr, *_t;
    _hdr = pools_hdr[m];
    /* if(_hdr->pid != myhdr->pid) return -1;*/
    if(myhdr->drl > LIMIT_SLAB_BYTE) return -1;
    /* clear nasty hdr */
    for(;_hdr->next;_hdr=_hdr->next){
        _t = _hdr->next;
        if(_t->flag == H_FALSE){
            _hdr->next = _t->next;
            freeHdr(_t);
            if(!_hdr->next) break;
        }
    }
    for (; _hdr->next; _hdr=_hdr->next );;
    _hdr->next = myhdr;
    return 0;
}               /* -----  end of function addHdr  ----- */
int addUlist (ULIST * mlist, int m)
Definition at line 168 of file pool_worker.c.
References freeUList(), H_FALSE, and pools_ulist.
Referenced by main().
{
    ULIST *_ulist, *_t;
    _ulist = pools_ulist[m];
    /*if(_ulist->pid != mlist->pid) return -1; */
    /* clear nasty ulist */
    for(; _ulist->next; _ulist=_ulist->next){
        _t = _ulist->next;
        if(_t->flag == H_FALSE){
            _ulist->next = _t->next;
            freeUList(_t);
            if(!_ulist->next) break;
        }
    }
    for(;_ulist->next;_ulist=_ulist->next);;
    _ulist->next = mlist;
    return 0;
}               /* -----  end of function addulist  ----- */
void freeHdr (HDR * fhdr)
Definition at line 198 of file pool_worker.c.
Referenced by addHdr(), and AuthPG().
{
    if(!fhdr)return;
    if(fhdr->key)
        free(fhdr->key);
    if(fhdr->dr)
        free(fhdr->dr);
    free(fhdr);
}               /* -----  end of function freeHdr  ----- */
void freeUList (ULIST * flist)
Definition at line 214 of file pool_worker.c.
Referenced by addUlist().
{
    if(!flist) return;
    if(flist->key)
        free(flist->key);
    free(flist);
}               /* -----  end of function freeUList  ----- */
void getslab (HITEM * hitem, SLABPACK * dest)
Definition at line 107 of file pool_worker.c.
References hsms(), and pools_hslab.
Referenced by hkey().
{
    HITEM *_ph = hitem;
    HSLAB *_ps;
    int i;
    if(!_ph) return;
    i = hsms(_ph->psize);
    _ps = pools_hslab[i];
    for(; _ps; _ps=_ps->next){
        if(_ps->id == _ph->sid){
            dest->pack = calloc(_ph->drl, sizeof(char));
            if(!dest->pack) return;
            memcpy(dest->pack, _ps->sm+_ph->sa*_ph->psize, _ph->drl);
            dest->len = _ph->drl;
            return;
        }
    }
}               /* -----  end of function getslab  ----- */
HITEM* hfind (char * key, ub4 keyl)
Definition at line 43 of file pool_worker.c.
References HIT_LOCK, HIT_UNLOCK, HITEM_SWITCH, jenkins_one_at_a_time_hash(), lookup(), MAX_HARU_POOL, pools_haru_pool, pools_harug, pools_hitem, pools_htab, and pools_tlist.
Referenced by hkey().
{
    ub4 hval,hjval, y;
    HITEM *ph;
    TLIST *tlist;
    int i;
    hval = lookup((ub1 *)key, keyl, 0);
    hjval = jenkins_one_at_a_time_hash((ub1 *)key, keyl);
    tlist = pools_tlist->next;
    HITEM_SWITCH((y=(hval&pools_htab->mask)));
    ph = pools_hitem[y];
    if(!ph) return NULL;
    while ( ph ) {
        if(hval == ph->hval &&
            (keyl == ph->keyl) &&
            (hjval == ph->hjval) &&
            (ph->drl > 0)
            ){
                if(!tlist)printf("tlist is null\n");
                while ( tlist ) {
                    /*  has a bug */
                    if(tlist->keyl >0 && strstr(key, tlist->key)){
                        /* over time */
                        if(tlist->utime > ph->utime) return NULL;
                    }
                    tlist = tlist->next;
                }
                HIT_LOCK();
                ph->ahit++;
                pools_htab->hit++;
                for(i=0; i<MAX_HARU_POOL; i++){
                    if( pools_haru_pool[i].phitem == ph ){
                        pools_haru_pool[i].hit++;
                        break;
                    }
                }
                if(pools_haru_pool[pools_harug->max].hit < pools_haru_pool[i].hit){
                    pools_harug->max = i;
                }
                if(pools_haru_pool[pools_harug->mix].hit > pools_haru_pool[i].hit){
                    pools_harug->mix = i;
                }
                HIT_UNLOCK();
                return ph;
        }
        ph = ph->next;
    }
    return NULL;
}               /* -----  end of function hfind  ----- */
void hkey (char * key, ub4 keyl, SLABPACK * dest)
Definition at line 29 of file pool_worker.c.
References getslab(), and hfind().
Referenced by main().
{
    HITEM *_h;
    _h = hfind(key, keyl);
    getslab(_h, dest);
}               /* -----  end of function hkey  ----- */