fdbc: hashtable/pool_init.c File Reference
hashtable/pool_init.c File Reference
#include "pool_init.h"
Functions
void hcreate (int isize)
void inithslab (int i)
HSLAB * hslabnull ()
HSLAB * hslabcreate (int i)
int hslabclass (void)
HITEM ** inithitem (ub4 len)
HITEM * hitemcreate ()
void freehitem (HITEM **_h, ub4 len)
HDR ** inithdr ()
HDR * hdrcreate ()
ULIST ** initulist ()
Function Documentation
void freehitem (HITEM ** _h, ub4 len)
Definition at line 232 of file pool_init.c.
Referenced by hgrow().
{
    int i;
    if(!*_h) return;
    if(!_h) return;
    for(i=0; i<len; i++){
        if(!_h[i]) free(_h[i]);
    }
    free(*_h);
}               /* -----  end of function freehitem  ----- */
void hcreate (int isize)
Definition at line 27 of file pool_init.c.
References hitem_group, hslabclass(), inithdr(), inithitem(), inithslab(), initulist(), MAX_HARU_POOL, pools_fslab, pools_haru_pool, pools_harug, pools_hdr, pools_hitem_row, pools_htab, pools_tlist, pools_ulist, work_lock_bytes, work_lock_hit, and work_lock_miss.
Referenced by main().
{
    int i;
    ub4 len;
    int max_slab;
    len = ((ub4)1<<isize);
    pools_htab = (HTAB *)calloc(1, sizeof(HTAB));
    if(pools_htab == NULL){
        perror("pools_htab calloc error");
        exit(1);
    }
    pools_htab->mask = len - 1;
    pools_htab->logsize = len;
    pools_htab->count = 0;
    pools_htab->bcount = 0;
    pools_htab->lcount = 0;
    pools_htab->hit = 0;
    pools_htab->miss = 0;
    pools_htab->set = 0;
    pools_htab->get = 0;
    pools_htab->bytes = 0;
    bzero(pools_htab->hslab_stat,  sizeof(pools_htab->hslab_stat));
    pools_harug = (HARUG *)calloc(1, sizeof(HARUG));
    pools_harug->step = 0;
    for(i=0; i < MAX_HARU_POOL; i++){
        /*pools_harug->pools_haru_pool[i] = (HARU *)calloc(1, sizeof(HARU));
        if(pools_harug->pools_haru_pool[i] == NULL){
            perror("pools_haru_pool callo error ");
            exit(1);
        }*/
        pools_harug->haru_pool[i].phitem = NULL;
    }
    pools_haru_pool = pools_harug->haru_pool;
    pools_hitem_row = calloc(len, sizeof(ub4));
    hitem_group = (HG *)calloc(1, sizeof(HG));
    hitem_group->bucket = pools_htab->logsize;
    hitem_group->usable = inithitem ( (ub4) len );
    hitem_group->move = NULL;
    pools_hdr = inithdr();
    pools_tlist = (TLIST *)calloc(1, sizeof(TLIST));
    pools_ulist = initulist();
    max_slab = hslabclass();
    if(max_slab > 0){
        inithslab ( max_slab );
    }
    /*pthread_mutex_init(&work_lock_fslab, NULL);  */
    pthread_mutex_init(&work_lock_hit, NULL);
    pthread_mutex_init(&work_lock_miss, NULL);
    pthread_mutex_init(&work_lock_bytes, NULL);
    pools_fslab = (FSLAB *)calloc(1, sizeof(FSLAB));
    pools_fslab->psize = 0;
    pools_fslab->sid = 0;
    pools_fslab->sa = 0;
    pools_fslab->next = NULL;
    return ;
}               /* -----  end of function hcreate  ----- */
HDR* hdrcreate ()
Definition at line 270 of file pool_init.c.
Referenced by inithdr().
                   {
    HDR *d;
    d = (HDR *)calloc(1, sizeof(HDR));
    if(d){
        d->key = NULL;
        d->keyl = 0;
        d->stime = 0;
        d->flag = 0;
        d->dr = NULL;
        d->drl = 0;
        d->next = NULL;
    }
    return d;
}               /* -----  end of function hdrcreate  ----- */
HITEM* hitemcreate ()
Definition at line 205 of file pool_init.c.
Referenced by haddHitem(), and inithitem().
                    {
    HITEM *h;
    h = (HITEM *)calloc(1, sizeof(HITEM));
    if(h){
        h->key = NULL;
        h->keyl = 0;
        h->drl = 0;
        h->psize = 0;
        h->sid = 0;
        h->sa = 0;
        h->hval = 0;
        h->hjval = 0;
        h->utime = 0;
        h->ahit = 0;
        h->amiss = 0;
        h->next = NULL;
    }
    return h;
}               /* -----  end of function hitemcreate  ----- */
int hslabclass (void)
Definition at line 157 of file pool_init.c.
References CHUNK_ALIGN_BYTES, conn_global, MAX_SLAB_BYTE, MAX_SLAB_CLASS, SLAB_BEGIN, and slabclass.
Referenced by hcreate().
                       {
    int size = SLAB_BEGIN;
    int i=0;
    while (i < MAX_SLAB_CLASS && size <= MAX_SLAB_BYTE / conn_global->factor) {
        if (size % CHUNK_ALIGN_BYTES)
            size += CHUNK_ALIGN_BYTES - (size % CHUNK_ALIGN_BYTES);
        /*if((item_size_max / size) < 2) break;
        printf("slab class  chunk size %9u perslab %7u\n",
                     size, (MAX_SLAB_BYTE / size));*/
        slabclass[i].size = size;
        slabclass[i].chunk = (MAX_SLAB_BYTE / size);
        /*printf("slabclass: size:%d, chunk:%d\n", slabclass[i].size, slabclass[i].chunk);*/
        i++;
        size *= conn_global->factor;
    }
    slabclass[i].size = MAX_SLAB_BYTE;
    slabclass[i].chunk = 1;
    return (++i);
}               /* -----  end of function hslabclass  ----- */
HSLAB* hslabcreate (int i)
Definition at line 135 of file pool_init.c.
References BYTES_LOCK, BYTES_UNLOCK, hslabnull(), MAX_SLAB_BYTE, pools_htab, and slabclass.
Referenced by findslab().
{
    HSLAB *h;
    h = hslabnull();
    h->sm = (ub1 *)calloc(MAX_SLAB_BYTE, sizeof(ub1));
    if(!h->sm)perror("h sm calloc error\n");
    h->sf = slabclass[i].chunk;
    BYTES_LOCK();
    pools_htab->bytes += MAX_SLAB_BYTE;
    pools_htab->hslab_stat[i]++;
    BYTES_UNLOCK();
    return h;
}               /* -----  end of function hslabcreate  ----- */
HSLAB* hslabnull ()
Definition at line 116 of file pool_init.c.
Referenced by hslabcreate(), and inithslab().
                     {
    HSLAB *_h;
    _h = (HSLAB *)calloc(1, sizeof(HSLAB));
    if(_h != NULL){
        _h->sm = NULL;
        _h->ss = 0;
        _h->sf = 0;
        _h->id = 0;
        _h->next = NULL;
    }
    return _h;
}               /* -----  end of function hslabnull  ----- */
HDR** inithdr ()
Definition at line 252 of file pool_init.c.
References conn_global, and hdrcreate().
Referenced by hcreate().
                  {
    int i;
    HDR **d;
    d = (HDR **) calloc(conn_global->process_num, sizeof(HDR));
    for(i=0; i<conn_global->process_num; i++){
        d[i] = hdrcreate();
    }
    return d;
}               /* -----  end of function inithdr  ----- */
HITEM** inithitem (ub4 len)
Definition at line 186 of file pool_init.c.
References hitemcreate().
Referenced by hcreate(), and hgrow().
{
    int i;
    HITEM **hitem;
    hitem = (HITEM **)calloc(len, sizeof(HITEM));
    if(hitem == NULL) return NULL;
    /* pools_hitem head not store anything */
    for (i=0; i<len; ++i) {
        hitem[i] = hitemcreate();
    }
    return hitem;
}               /* -----  end of function inithitem  ----- */
void inithslab (int i)
Definition at line 102 of file pool_init.c.
References hslabnull(), and pools_hslab.
Referenced by hcreate().
{
    int m;
    pools_hslab = (HSLAB **)calloc(i, sizeof(HSLAB));
    for(m=0; m<i; m++){
        pools_hslab[m] = hslabnull();
    }
}               /* -----  end of static function inithslab  ----- */
ULIST** initulist ()
Definition at line 291 of file pool_init.c.
References conn_global.
Referenced by hcreate().
                      {
    ULIST **u;
    int i;
    u = (ULIST **)calloc(conn_global->process_num, sizeof(ULIST));
    for(i=0; i<conn_global->process_num; i++){
        u[i] = (ULIST *)calloc(1, sizeof(ULIST));
        if(u[i]){
            u[i]->key = NULL;
            u[i]->keyl = 0;
            u[i]->utime = 0;
            u[i]->flag = 0;
            u[i]->next = NULL;
        }
    }
    return u;
}               /* -----  end of function initulist  ----- */