fdbc: signal_lib.c File Reference
signal_lib.c File Reference
#include "signal_lib.h"
Functions
void sig_handler (const int sig)
void set_signal (void)
Function Documentation
void set_signal (void)
Definition at line 19 of file signal_lib.c.
References sig_handler().
Referenced by main().
                     {
        signal(SIGINT, sig_handler);
        signal(SIGTERM, sig_handler);
        signal(SIGQUIT, sig_handler);
        signal(SIGKILL, sig_handler);
        signal(SIGHUP, sig_handler);
        return;
}
void sig_handler (const int sig)
Definition at line 13 of file signal_lib.c.
Referenced by set_signal().
{
    exit(-1);
        return;
}