fdbc: strawberry.c File Reference
strawberry.c File Reference
#include <error.h>
#include "log_lib.h"
#include "thread_lib.h"
#include "conf_lib.h"
#include "action_lib.h"
#include "daemon_lib.h"
#include "signal_lib.h"
#include "config_global.h"
#include "./modules/modules.h"
#include "./hashtable/pool_init.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 21 of file strawberry.c.
References conf_init(), conn_get_global(), conn_global, conn_init_global(), conn_new(), d_log(), daemon_init(), hcreate(), main_base, notify_token_thread, NT_FREE, rq_init(), save_pid(), server_socket_unix(), set_signal(), Socket_Init(), token_thread_init(), and work_thread_init().
{
    int listen_fd, unix_sock;
    pid_t pid;
    int fds[2];
        int h, max_ring_queue;
        char *c, pid_file[500], buf[1];
        ssize_t do_daemonize = 0;
    extern int process_num;
    char help[]=" -c etc/suning.cnf\n \
                Usage: \n \
                -c which loading suning.cnf \n \
                -d daemon run \n";
    set_signal();
    if(argc < 2){
        printf("%s%s\n", argv[0], help);
        exit(-1);
    }
    c = NULL;
        while((h = getopt(argc, argv, "c:d")) != -1){
                switch(h){
                        case 'c':
                                c = optarg;
                                break;
                        case 'd':
                                do_daemonize = 1;
                                break;
                        default:
                                printf("%s --help\n", argv[0]);
                                exit(-1);
                }
        }
    conn_init_global();
    if(c){
            conf_init(c);
        conn_get_global();
    }
        d_log("snooker:0.0.1 start ...");
        if(do_daemonize == 1 || conn_global->do_daemonize == 1){
                daemon_init(argv[0], 0);
                if(strlen(conn_global->pid_file) > 0)strcpy(pid_file, conn_global->pid_file);
                else strcpy(pid_file, "/var/run/strawberry.pid");
                save_pid(getpid(), pid_file);
        }
    /* register moduels
        modules_register();*/
    unix_sock = conn_global->unix_sock;
        if(0 == unix_sock)
                listen_fd = Socket_Init();
        else
                listen_fd = server_socket_unix();
        if (listen_fd < 0){
                perror( "listen failed");
                exit(-1);
        }
    hcreate(8);
    //rq_init(MAXCONN);
    rq_init(2);
    work_thread_init(conn_global->process_num);
    token_thread_init();
    notify_token_thread = NT_FREE;
    main_base = event_init();
    conn_new(listen_fd, main_base);
    event_base_loop(main_base, 0);
    return 0;
}