fdbc: thread_lib.h File Reference
thread_lib.h File Reference
#include <event.h>
#include <pthread.h>
#include <unistd.h>
#include <malloc.h>
#include <string.h>
#include <sys/eventfd.h>
#include "socket_lib.h"
#include "pg_protocol.h"
Data Structures
struct LIBEVENT_TOKEN_THREAD
struct LIBEVENT_WORK_THREAD
struct FC_ITEM
struct RQ
struct WTQ
struct conn
Defines
#define MAX_BACKEND_SESSION 128
#define ERROR_BREAK(client_sfd, send_val, send_val_len, type_val)
#define FIND_RQ(cq, stat)
#define FIND_WTQ(cq, stat)
#define FIND_WTQPID(cq, stat)
#define FIND_Q(type, cq, table, stat)
Enumerations
enum RING_JOB_STATE { JOB_FREE = 0, JOB_HAS, JOB_WORKING }
enum NOTIFY_TOKEN_STATE { NT_FREE = 0, NT_HAS, NT_WORKING }
Functions
void work_thread_init (int nthreads)
void setup_thread (LIBEVENT_WORK_THREAD *me)
void create_worker (void *(*func)(void *), void *arg)
void * worker_libevent (void *arg)
void libevent_work_thread (int fd, short ev, void *arg)
void token_thread_init ()
void setup_token (void *(*func)(void *), void *arg)
void * main_token_thread (void *arg)
void libevent_token_thread (int fd, short ev, void *arg)
RQ * rq_item_init ()
int rq_init (int numbers)
int rq_push (int client_fd)
RQ * rq_pop ()
void rq_free (RQ *child)
WTQ * wtq_init ()
void wtq_push ()
WTQ * wtq_pop ()
Variables
conn * conns
RQ * rq_queue_head
RQ * rq_queue_tail
WTQ * wtq_queue_head
WTQ * wtq_queue_tail
struct event_base * main_base
LIBEVENT_TOKEN_THREAD * token_thread
NOTIFY_TOKEN_STATE notify_token_thread
LIBEVENT_WORK_THREAD * work_threads
pthread_mutex_t init_work_lock
pthread_cond_t init_work_cond
int token_efd
Define Documentation
#define ERROR_BREAK (client_sfd, send_val, send_val_len, type_val)
Value:
do {    \
    (type_val) = 0;                                                \
    Socket_Send((client_sfd), (send_val), (send_val_len)); \
} while (0)
Definition at line 24 of file thread_lib.h.
#define FIND_Q (type, cq, table, stat)
Value:
do{\
    type *rq_head = (cq);             \
    do{                             \
        if(rq_head->table==(stat)) break; \
        rq_head = rq_head->next;            \
    }while(rq_head!=(cq));                  \
    (cq) = rq_head;                       \
}while(0)
Definition at line 41 of file thread_lib.h.
#define FIND_RQ (cq, stat)
Value:
do{\
    FIND_Q(RQ, cq, isjob, stat); \
}while(0)
Definition at line 29 of file thread_lib.h.
Referenced by rq_pop(), and rq_push().
#define FIND_WTQ (cq, stat)
Value:
do{\
    FIND_Q(WTQ, cq, isjob, stat); \
}while(0)
Definition at line 33 of file thread_lib.h.
Referenced by libevent_token_thread().
#define FIND_WTQPID (cq, stat)
Value:
do{\
    FIND_Q(WTQ, cq, pid, stat); \
}while(0)
Definition at line 37 of file thread_lib.h.
Referenced by libevent_work_thread().
#define MAX_BACKEND_SESSION 128
Definition at line 22 of file thread_lib.h.
Enumeration Type Documentation
enum NOTIFY_TOKEN_STATE
Enumerator:
NT_FREE
NT_HAS
NT_WORKING
Definition at line 57 of file thread_lib.h.
             {
    NT_FREE=0,  /* default 0 ,it's 1 has a job, 2 working */
    NT_HAS,
    NT_WORKING
} NOTIFY_TOKEN_STATE;
enum RING_JOB_STATE
Enumerator:
JOB_FREE
JOB_HAS
JOB_WORKING
Definition at line 51 of file thread_lib.h.
             {
    JOB_FREE=0,  /* default 0 ,it's 1 has a job, 2 working */
    JOB_HAS,
    JOB_WORKING
} RING_JOB_STATE;
Function Documentation
void create_worker (void *(*)(void *) func, void * arg)
Definition at line 186 of file thread_lib.c.
References d_log().
Referenced by work_thread_init().
{
    pthread_t       thread;
    pthread_attr_t  attr;
    int ret;
    pthread_attr_init(&attr);
    if ((ret = pthread_create(&thread, &attr, func, arg)) != 0) {
        d_log("Can't create thread");
        printf("here---\n");
        exit(1);
    }
}
void libevent_token_thread (int fd, short ev, void * arg)
Definition at line 275 of file thread_lib.c.
References FIND_WTQ, JOB_FREE, JOB_HAS, JOB_WORKING, LIBEVENT_WORK_THREAD::no, notify_token_thread, LIBEVENT_WORK_THREAD::notify_write_fd, NT_FREE, NT_WORKING, rq_pop(), token_efd, work_threads, and wtq_queue_tail.
Referenced by token_thread_init().
{
    uint64_t u;
    ssize_t s;
    s = read(token_efd, &u, sizeof(uint64_t));
    if (s != sizeof(uint64_t)){
        printf("s is error\n");
    }
    notify_token_thread = NT_WORKING;
    do{
        RQ *rq_item = rq_pop();
        if(rq_item == NULL) break;
        if(rq_item->isjob == JOB_HAS) {
            WTQ *work_child = wtq_queue_tail;
            FIND_WTQ(work_child, JOB_FREE);
            if(work_child->isjob == JOB_FREE){
                rq_item->isjob = JOB_WORKING;
                work_child->rq_item = rq_item;
                work_child->isjob = JOB_HAS;
                LIBEVENT_WORK_THREAD *thread;
                thread = work_threads + work_child->no;
                if(thread == NULL){
                    printf("thread null \n");
                    rq_item->isjob = JOB_HAS;
                    work_child->isjob = JOB_FREE;
                    break;
                }
                if(write(thread->notify_write_fd, "", 1) != 1){
                    printf("write thread error\n");
                }
            }
        }
        else{
            printf("break\n");
            break;
        }
    }while(1);
    notify_token_thread = NT_FREE;
}
void libevent_work_thread (int fd, short ev, void * arg)
Definition at line 20 of file thread_lib.c.
References AuthPG(), SESSION_SLOTS::backend_fd, Client_Init(), conf_get(), d_log(), FIND_WTQPID, JOB_FREE, JOB_HAS, JOB_WORKING, notify_token_thread, NT_FREE, PGStartupPacket3(), resolve_slot(), Socket_Send(), LIBEVENT_WORK_THREAD::thread_id, token_efd, and wtq_queue_tail.
Referenced by setup_thread().
{
    LIBEVENT_WORK_THREAD *me =(LIBEVENT_WORK_THREAD *)arg;
    char buf[1], *pv_buf;
    int ffd;
    WTQ *work_child;
    SESSION_SLOTS *slot;
    int pg_fds, m, pg_len, client_len, pack_len;
    PACK *start_pack;
    SESSION_SLOTS *_slot;
    if (read(fd, buf, 1) != 1)
            d_log("error Can't read from libevent pipe");
    work_child = wtq_queue_tail;
    wtq_queue_tail = wtq_queue_tail->next;
   // printf("thread_id:%llu\n", me->thread_id);
    FIND_WTQPID(work_child, me->thread_id);
    if(work_child->isjob == JOB_HAS)
        work_child->isjob = JOB_WORKING;
    else{
         goto err;
    }
    //rq_child = child->rqchild;
    //pg_fds = Client_Init(conf_get("pg_host"), atoi(conf_get("pg_port")));
    //cmd = (char *)calloc(1, sizeof(char));
    ffd = work_child->rq_item->frontend->ffd;
    start_pack = (PACK *)calloc(1, sizeof(PACK));
    start_pack->pack = (char *)calloc(1, sizeof(char));
    pack_len = PGStartupPacket3(ffd, start_pack);  /*  1. F -> B */
    if(pack_len == -1)goto ok;
    pg_fds = Client_Init(conf_get("pg_host"), atoi(conf_get("pg_port")));
    if(pg_fds == -1){
        if(start_pack->pack != NULL)free(start_pack->pack);
        start_pack->pack = NULL;
        goto bad;
    }
    pg_len = Socket_Send(pg_fds, start_pack->pack, pack_len);
    if(pg_len != pack_len) goto bad;
    _slot = resolve_slot(start_pack->pack);
   if(_slot->backend_fd == 0){
       /*  pg_fds = Client_Init(conf_get("pg_host"), atoi(conf_get("pg_port")));
        if(pg_fds == -1){
            if(start_pack->pack != NULL)free(start_pack->pack);
            start_pack->pack = NULL;
            goto bad;
        }
        pg_len = Socket_Send(pg_fds, start_pack->pack, pack_len);
         */
        if(pg_len != pack_len) goto bad;
        if(AuthPG(pg_fds, ffd, _slot, work_child->no)==-1){
            //printf("auth error\n");
            //            goto bad;
            //                    }else{
            //
            //                            }
            //                                }
            //
            //
            //                    }
        }else{
        }
    }
    work_child->isjob = JOB_FREE;
    //rq_free(rq_child);
    //child->rqchild = NULL;
    if(notify_token_thread == NT_FREE){
        uint64_t u;
        ssize_t s;
        u = 1;
        s = write(token_efd, &u , sizeof(uint64_t));
        if(s != sizeof(uint64_t)){
            printf("write error s:%d\n", s);
        }
        //printf("token_efd\n");
    }
    ok:
    bad:
    err:
        close(work_child->rq_item->frontend->ffd);
        work_child->rq_item->isjob = JOB_FREE;
        work_child->isjob = JOB_FREE;
        printf("end\n");
        //rq_free(rq_child);
        //(void)0;
    /* clean_sfd:
        if(Socket_Close(rq_child->client->cfd) == -1) d_log("close fd error!\n");
        rq_child->isjob = JOB_FREE;
    */
}
void* main_token_thread (void * arg)
Definition at line 270 of file thread_lib.c.
References LIBEVENT_TOKEN_THREAD::base.
Referenced by token_thread_init().
{
    LIBEVENT_TOKEN_THREAD *me = arg;
    event_base_loop(me->base, 0);
}
void rq_free (RQ * child)
Definition at line 412 of file thread_lib.c.
References JOB_FREE.
                       {
    if(child != NULL){
        close(child->frontend->ffd);
        /*  if(Socket_Close(child->client->cfd) == -1) d_log("close fd error!\n");*/
        child->isjob = JOB_FREE;
        if(child->frontend != NULL)
            free(child->frontend);
        free(child);
    }
}
int rq_init (int numbers)
Definition at line 353 of file thread_lib.c.
References rq_item_init(), rq_queue_head, and rq_queue_tail.
Referenced by main().
{
    int n;
    RQ *rq_child;
    if(numbers < 1) return -1;
    rq_queue_head = rq_item_init();
    rq_queue_tail = rq_queue_head;
    for(n=1; n<numbers; n++){
        rq_child = rq_item_init();
        rq_queue_head->next = rq_child;
        rq_queue_head = rq_child;
    }
    rq_queue_head->next = rq_queue_tail;
    rq_queue_head = rq_queue_tail;
    return 0;
}
RQ* rq_item_init ()
Definition at line 329 of file thread_lib.c.
References d_log(), and JOB_FREE.
Referenced by rq_init().
                  {
    RQ *rq;
    rq = (RQ *)calloc(1, sizeof(RQ));
    if(rq == NULL){
        d_log("Can't calloc for RQ");
        exit(1);
    }
    rq->frontend = (FC_ITEM *)calloc(1, sizeof(FC_ITEM));
    if(rq->frontend == NULL){
        d_log("Can't calloc for CC_ITEM");
        exit(1);
    }
    rq->isjob = JOB_FREE;
    rq->next = NULL;
    return rq;
}
RQ* rq_pop ()
Definition at line 394 of file thread_lib.c.
References FIND_RQ, JOB_HAS, and rq_queue_tail.
Referenced by libevent_token_thread().
            {
    RQ *rq_i;
    FIND_RQ(rq_queue_tail, JOB_HAS);
    if(rq_queue_tail->isjob != JOB_HAS){
        return NULL;
    }
    rq_i = rq_queue_tail;
    rq_queue_tail = rq_queue_tail->next;
    return rq_i;
}
int rq_push (int client_fd)
Definition at line 377 of file thread_lib.c.
References FIND_RQ, get_sec(), JOB_FREE, JOB_HAS, and rq_queue_head.
Referenced by on_accept().
{
    FIND_RQ(rq_queue_head, JOB_FREE);
    if(rq_queue_head->isjob != JOB_FREE) return -1;
    rq_queue_head->frontend->ffd = client_fd;
    rq_queue_head->frontend->ctime = get_sec() ;
    rq_queue_head->isjob = JOB_HAS;
    rq_queue_head = rq_queue_head->next;
    return 0;
}
void setup_thread (LIBEVENT_WORK_THREAD * me)
Definition at line 168 of file thread_lib.c.
References LIBEVENT_WORK_THREAD::base, d_log(), libevent_work_thread(), LIBEVENT_WORK_THREAD::notify_event, and LIBEVENT_WORK_THREAD::notify_read_fd.
Referenced by work_thread_init().
{
    me->base = event_init();
    if (! me->base) {
        d_log("error Can't allocate event base");
        exit(1);
    }
    /* Listen for notifications from other threads */
    event_set(&me->notify_event, me->notify_read_fd,
              EV_READ | EV_PERSIST, libevent_work_thread, me);
    event_base_set(me->base, &me->notify_event);
    if (event_add(&me->notify_event, 0) == -1) {
        d_log("Can't monitor libevent notify pipe");
        exit(1);
    }
}
void setup_token (void *(*)(void *) func, void * arg)
Definition at line 258 of file thread_lib.c.
References d_log().
Referenced by token_thread_init().
{
    pthread_t       thread;
    pthread_attr_t  attr;
    int ret;
    pthread_attr_init(&attr);
    if ((ret = pthread_create(&thread, &attr, func, arg)) != 0) {
        d_log("Can't create thread");
        exit(1);
    }
}
void token_thread_init ()
Definition at line 235 of file thread_lib.c.
References LIBEVENT_TOKEN_THREAD::base, d_log(), libevent_token_thread(), main_token_thread(), LIBEVENT_TOKEN_THREAD::notify_event, setup_token(), token_efd, and token_thread.
Referenced by main().
{
    token_thread = (LIBEVENT_TOKEN_THREAD *)calloc(1, sizeof(LIBEVENT_TOKEN_THREAD));
    token_thread->base = event_base_new();
    if (! token_thread->base) {
        d_log("error Can't allocate event base");
        exit(1);
    }
    token_efd = eventfd(0, 0);
    if(token_efd == -1) exit(1);
    /* Listen for notifications from other threads */
    event_set(&token_thread->notify_event, token_efd,
              EV_READ | EV_PERSIST, libevent_token_thread, token_thread);
    event_base_set(token_thread->base, &token_thread->notify_event);
    if (event_add(&token_thread->notify_event, 0) == -1) {
        d_log("Can't monitor libevent notify pipe");
        exit(1);
    }
    setup_token(main_token_thread, token_thread);
}
void work_thread_init (int nthreads)
Definition at line 132 of file thread_lib.c.
References create_worker(), init_count, init_work_cond, init_work_lock, LIBEVENT_WORK_THREAD::no, LIBEVENT_WORK_THREAD::notify_read_fd, LIBEVENT_WORK_THREAD::notify_write_fd, setup_thread(), work_threads, worker_libevent(), wtq_queue_head, and wtq_queue_tail.
Referenced by main().
{
    int i;
    work_threads = (LIBEVENT_WORK_THREAD *)calloc(nthreads, sizeof(LIBEVENT_WORK_THREAD));
    if(!work_threads){
        exit(1);
    }
    wtq_queue_tail = wtq_queue_head = NULL;
    pthread_mutex_init(&init_work_lock, NULL);
    pthread_cond_init(&init_work_cond, NULL);
    for(i=0; i< nthreads; i++){
        int fds[2];
        if(pipe(fds)){
        }
        work_threads[i].notify_read_fd = fds[0];
        work_threads[i].notify_write_fd = fds[1];
        work_threads[i].no = i;
        setup_thread(&work_threads[i]);
    }
    for(i=0; i<nthreads; i++){
        create_worker(worker_libevent, &work_threads[i]);
    }
    pthread_mutex_lock(&init_work_lock);
    while (init_count < nthreads) {
        pthread_cond_wait(&init_work_cond, &init_work_lock);
    }
    wtq_queue_head->next = wtq_queue_tail;
    pthread_mutex_unlock(&init_work_lock);
}
void* worker_libevent (void * arg)
Definition at line 199 of file thread_lib.c.
References LIBEVENT_WORK_THREAD::base, init_count, init_work_cond, init_work_lock, LIBEVENT_WORK_THREAD::no, LIBEVENT_WORK_THREAD::thread_id, wtq_init(), wtq_queue_head, and wtq_queue_tail.
Referenced by work_thread_init().
{
    WTQ *work_child;
    LIBEVENT_WORK_THREAD *me = (LIBEVENT_WORK_THREAD *)arg;
    /* Any per-thread setup can happen here; thread_init() will block until
     * all threads have finished initializing.
     */
    pthread_mutex_lock(&init_work_lock);
    work_child = wtq_init();
    work_child->pid = pthread_self();
    me->thread_id = work_child->pid;
    work_child->no = me->no;
    if(wtq_queue_head == NULL){
        wtq_queue_tail = wtq_queue_head = work_child;
    }else{
        wtq_queue_head->next = work_child;
        wtq_queue_head = work_child;
    }
    init_count++;
    /*  error_add(pthread_self());*/
    pthread_cond_signal(&init_work_cond);
    pthread_mutex_unlock(&init_work_lock);
    wtq_queue_head->next = wtq_queue_tail;
    event_base_loop(me->base, 0);
}
WTQ* wtq_init ()
Definition at line 426 of file thread_lib.c.
References MAX_BACKEND_SESSION.
Referenced by worker_libevent().
               {
    WTQ *work_child;
    work_child = (WTQ *)calloc(1, sizeof(WTQ));
    work_child->rq_item = NULL;
    bzero(work_child->slots, MAX_BACKEND_SESSION);
    work_child->next = NULL;
    return work_child;
}
WTQ* wtq_pop ()
void wtq_push ()
Variable Documentation
conn* conns
Definition at line 116 of file thread_lib.h.
Referenced by conn_new().
pthread_cond_t init_work_cond
Definition at line 132 of file thread_lib.h.
Referenced by work_thread_init(), and worker_libevent().
pthread_mutex_t init_work_lock
Definition at line 131 of file thread_lib.h.
Referenced by work_thread_init(), and worker_libevent().
struct event_base* main_base
Definition at line 124 of file thread_lib.h.
Referenced by main().
NOTIFY_TOKEN_STATE notify_token_thread
Definition at line 127 of file thread_lib.h.
Referenced by libevent_token_thread(), libevent_work_thread(), main(), and on_accept().
RQ* rq_queue_head
Definition at line 118 of file thread_lib.h.
Referenced by rq_init(), and rq_push().
RQ* rq_queue_tail
Definition at line 119 of file thread_lib.h.
Referenced by rq_init(), and rq_pop().
int token_efd
Definition at line 135 of file thread_lib.h.
Referenced by libevent_token_thread(), libevent_work_thread(), on_accept(), and token_thread_init().
LIBEVENT_TOKEN_THREAD* token_thread
Definition at line 126 of file thread_lib.h.
Referenced by token_thread_init().
LIBEVENT_WORK_THREAD* work_threads
Definition at line 130 of file thread_lib.h.
Referenced by libevent_token_thread(), and work_thread_init().
WTQ* wtq_queue_head
Definition at line 121 of file thread_lib.h.
Referenced by work_thread_init(), and worker_libevent().
WTQ* wtq_queue_tail
Definition at line 122 of file thread_lib.h.
Referenced by libevent_token_thread(), libevent_work_thread(), work_thread_init(), and worker_libevent().